#%RAML 1.0
title: PoomCI Dependency API
version: v1
baseUri: https://api.codingmatters.org/poom-ci
mediaType: application/json

/repositories:
   displayName: Repositories

   get:
      responses:
         200:
            body: Repository[]
         400:
            body: Error
         404:
            body: Error
         500:
            body: Error

   /{repository-id}:
      displayName: Repository
      uriParameters:
         repository-id: string

      get:
         responses:
            200:
               body: Repository
            400:
               body: Error
            404:
               body: Error
            500:
               body: Error

      put:
         body: Repository
         responses:
            200:
               body: Repository
            400:
               body: Error
            500:
               body: Error

      /produces:
         displayName: RepositoryModules
         post:
            body: Module[]
            responses:
               201:
                  headers:
                     Location: string
               400:
                  body: Error
               404:
                  body: Error
               500:
                  body: Error
         get:
            responses:
               200:
                  body: Module[]
               400:
                  body: Error
               404:
                  body: Error
               500:
                  body: Error

      /depends-on:
         displayName: RepositoryDependencies
         post:
            body: Module[]
            responses:
               201:
                  headers:
                     Location: string
               400:
                  body: Error
               404:
                  body: Error
               500:
                  body: Error
         get:
            responses:
               200:
                  body: Module[]
               400:
                  body: Error
               404:
                  body: Error
               500:
                  body: Error

      /downstream:
         displayName: RepositoryDownstreamRepositories
         get:
            responses:
               200:
                  body: Repository[]
               400:
                  body: Error
               404:
                  body: Error
               500:
                  body: Error



types:
   Repository:
      type: object
      properties:
         id: string
         name: string
         checkoutSpec: string
   Module:
      type: object
      properties:
         spec: string
         version: string

   Error:
      type: object
      properties:
         token: string
         code:
            enum: [
               ILLEGAL_RANGE_SPEC,
               UNEXPECTED_ERROR,
               RESOURCE_NOT_FOUND,
               ILLEGAL_RESOURCE_CREATION, ILLEGAL_RESOURCE_CHANGE, ILLEGAL_REQUEST,
               ILLEGAL_COLLECTION_CHANGE,
               ]
         description: string