---
pipeline:
  $conforms-to: [org.codingmatters.poom.ci.pipeline.StageProvider]
  stages:
    $list: $stage

  onSuccess:
    $list: $stage
  onError:
    $list: $stage

  env:
    $list:
      $value-object: org.codingmatters.value.objects.values.ObjectValue

  secrets:
    $list: $secret

stage:
  name: string
  timeout: long
  onlyWen:
    $list: string
  exec:
    $list: string

stageHolder:
  stage: $stage
  type:
    $enum: MAIN, ERROR, SUCCESS

secret:
  name: string
  content: string
  as:
    $enum: var, file