FROM openjdk:8-jdk-alpine

#RUN mkdir /storage/
#COPY ${project.artifactId}-${project.version}-uber.jar /var/service/service-uber.jar

#EXPOSE 9999
#EXPOSE 9998

#ENTRYPOINT ["java", "-jar", "/var/service/service-uber.jar", "--port", "9999"]
#CMD ["--mongo-host", "172.17.0.2", "--mongo-port", "27017", \
#"--io.flexio.services.accounts.client.AccountsAPIClient-service-url", "http://localhost:9999//accounts/v1",\
#"--io.flexio.services.document.model.client.DocumentModelAPIClient-service-url", "http://localhost:9999//document-model/v1",\
#"--io.flexio.services.object.storage.client.ObjectStorageAPIClient-service-url", "http://localhost:9999/object-storage/v1",\
#"--io.flexio.services.notifications.client.FlexioNotificationsClient-service-url", "http://localhost:9999/notifications/v1",\
#"--org.codingmatters.poom.client.PoomjobsJobRegistryAPIClient-service-url", "http://localhost:9999/jobs/v1",\
#"--org.codingmatters.poom.client.PoomjobsRunnerRegistryAPIClient-service-url", "http://localhost:9999/runners/v1",\
#"--io.flexio.services.document.producer.client.DocumentProducerClient-service-url", "http://localhost:9999/document-producer/v1",\
#"--object-store-path", "/storage",\
#"--jobs-database", "JOBS",\
#"--sseServicePath", "/sse", "--maxSseEventNumberToStore", "10", "--sseConnexionExpiryTimeInMinutes", "120",\
#"--ConverterThreadPoolSize", "2",\
#"--host", "0.0.0.0", "--port", "9998",\
#"--registryURL", "http://localhost:9999/jobs/v1"\
#]
